### ISSUE TITLE
NoMethodError - undefined method `nullif'

### ISSUE THREAD

**Issue by jnylen** [mwpastore/sinja#15]
I have an error trying to do has_many:
```
  ERROR -  NoMethodError - undefined method `nullif' for Server::ApiV3:Class:
 /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1624:in `block in compile!'
/home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1624:in `block in compile!': undefined method `nullif' for Server::ApiV3:Class (NoMethodError)
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1624:in `each_pair'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1624:in `compile!'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1601:in `route'
	from /vagrant/lib/sinja.rb:381:in `route'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1394:in `patch'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:338:in `prefixed'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:229:in `block (2 levels) in prefixed'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:338:in `prefixed'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:229:in `block (2 levels) in prefixed'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinja-1.2.5/lib/sinja/relationship_routes/has_many.rb:33:in `registered'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:244:in `block in register'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:242:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:242:in `register'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinja-1.2.5/lib/sinja/resource.rb:109:in `block (3 levels) in <module:Resource>'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:200:in `class_eval'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:200:in `block in new'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:190:in `initialize'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:190:in `new'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:190:in `new'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:220:in `namespace'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinja-1.2.5/lib/sinja/resource.rb:92:in `block (2 levels) in <module:Resource>'
```

It's just an simple:
```ruby
      has_many :programmes do
        fetch do
          resource.programmes
        end
      end
```

**Comment by mwpastore** [comment]
Are you registering the extension in your app?

**Comment by jnylen** [comment]
Yup,
```
module Server
  class ApiV3 < Sinatra::Base
    #use Sinja::MethodOverride
    register Sinja
  end
end
```

**Comment by jnylen** [comment]
Found out. It was my commented out string of:
`raise NotAcceptableError unless request.preferred_type.entry == MIME_TYPE || request.options?`

Do you suggest another why?

**Comment by jnylen** [comment]
Fixed.

**Comment by mwpastore** [comment]
No, I'm thoroughly perplexed, so I'm glad you figured it out. It's almost as if you had the v1.2.5 gem and your fork (at master tip) loaded simultaneously.
